CREATE OR REPLACE TRIGGER T_SALARY 
AFTER INSERT OR UPDATE ON LEAVE
FOR EACH ROW
DECLARE
    TEMP INT DEFAULT 0;
    U_SALARY INT;
BEGIN 
    SELECT SALARY INTO U_SALARY
    FROM PAYMENTS
    WHERE PAYMENTS.EMPLOYEE_ID = :NEW.EMPLOYEE_ID;

    TEMP:=(U_SALARY*:NEW.ATTENDANCE)/26;
    IF INSERTING THEN
        INSERT INTO LEAVE_SALARY VALUES(:NEW.EMPLOYEE_ID,:NEW.ATTENDANCE,TEMP);

    ELSIF UPDATING THEN
        INSERT INTO LEAVE_SALARY VALUES(:NEW.EMPLOYEE_ID,:NEW.ATTENDANCE,TEMP);
    END IF;
END;