CREATE OR REPLACE TRIGGER DUPLICATE_SALARY
BEFORE INSERT ON PAYMENTS
FOR EACH ROW
DECLARE
    COUNTER NUMBER;
BEGIN
    COUNTER:=0;
    SELECT COUNT(*) INTO COUNTER
    FROM PAYMENTS
    WHERE EMPLOYEE_ID=:NEW.EMPLOYEE_ID;

    IF(COUNTER>0) THEN
        RAISE_APPLICATION_ERROR(-20000, 'THE SALARY FOR EMPLOYEE_ID: '||:NEW.EMPLOYEE_ID||' ALREADY EXISTS.');
    END IF;
END;